/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/party-invites/{inviteToken}/rolling-papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 참가자용 롤링페이퍼 목록 조회
         * @description 초대 토큰으로 롤링페이퍼 목록과 상세 오버레이용 본문을 조회한다. 인증 없이도 조회 가능하다. Authorization header를 보낼 경우 유효한 Bearer token이어야 한다.
         */
        get: operations["getParticipantRollingPapers"];
        put?: never;
        /**
         * 롤링페이퍼 작성
         * @description 초대 토큰으로 롤링페이퍼를 작성한다. 인증 없이도 작성 가능하다. Authorization header를 보낼 경우 유효한 Bearer token이어야 한다.
         */
        post: operations["createRollingPaper"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/party-invites/{inviteToken}/realtime-participants/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 실시간 파티 입장 및 채팅 구독
         * @description 초대 토큰으로 실시간 파티에 입장하고, 즉시 채팅 스트림을 구독합니다.
         *
         *     **⚠️ Swagger UI에서는 직접 실행이 불가합니다.** 아래 curl 명령어를 사용하세요.
         *
         *     **입장 가능 조건**
         *     - 초대 링크가 만료되지 않아야 합니다
         *     - 파티 시작 5분 전부터 입장할 수 있습니다
         *
         *     **재입장**
         *     동일한 초대 토큰으로 다시 호출하면 닉네임·캐릭터가 덮어씌워지고, SSE 스트림이 새로 연결됩니다.
         *
         *     ---
         *
         *     **연결 직후 수신되는 이벤트**
         *
         *     | 이벤트 이름 | 설명 |
         *     |---|---|
         *     | `entered` | 입장 완료 정보 (participantToken + 기존 채팅 내역) |
         *
         *     **이후 실시간으로 수신되는 이벤트**
         *
         *     | 이벤트 이름 | 설명 |
         *     |---|---|
         *     | `message` | 새로 전송된 메시지 1건 |
         *     | `user-entered` | 참여자 입장 알림 |
         *     | `user-left` | 참여자 퇴장 알림 |
         *     | `party-ending` | 파티 종료 1분 전 알림 |
         *     | `party-ended` | 파티 종료 및 스트림 종료 알림 |
         *
         *     ---
         *
         *     **`entered` 이벤트 데이터 구조**
         *     ```json
         *     {
         *       "participantToken": "aB3xZ9qR",
         *       "messages": [
         *         {
         *           "messageId": 1,
         *           "content": "안녕하세요!",
         *           "senderNickname": "토끼왕",
         *           "senderCharacterId": 2,
         *           "senderCharacterImageUrl": "https://example.com/rabbit.png",
         *           "senderRole": "PARTICIPANT",
         *           "sentAt": "2026-05-07T10:00:00"
         *         }
         *       ]
         *     }
         *     ```
         *
         *     **`message` 이벤트 데이터 구조**
         *     ```json
         *     {
         *       "messageId": 2,
         *       "content": "반갑습니다!",
         *       "senderNickname": "곰돌이",
         *       "senderCharacterId": null,
         *       "senderCharacterImageUrl": null,
         *       "senderRole": "CELEBRANT",
         *       "sentAt": "2026-05-07T10:01:00"
         *     }
         *     ```
         *
         *     > `participantToken`: 이후 메시지 전송(`X-Participant-Token` 헤더)과 SSE 재연결에 사용합니다.
         *     > `senderCharacterId`는 캐릭터를 선택하지 않은 경우 `null`입니다.
         *
         *     ---
         *
         *     **curl 예시 (비로그인)**
         *     ```
         *     curl -N -X POST http://localhost:8080/api/v1/party-invites/{inviteToken}/realtime-participants/stream \
         *       -H "Content-Type: application/json" \
         *       -d '{"nickname":"토끼왕","characterId":1}'
         *     ```
         *
         *     **curl 예시 (로그인)**
         *     ```
         *     curl -N -X POST http://localhost:8080/api/v1/party-invites/{inviteToken}/realtime-participants/stream \
         *       -H "Content-Type: application/json" \
         *       -H "Authorization: Bearer {token}" \
         *       -d '{"nickname":"토끼왕","characterId":1}'
         *     ```
         *
         *     연결은 **15분** 후 자동 종료됩니다.
         */
        post: operations["enterAndSubscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/party-invites/{inviteToken}/participants/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원 초대장 참여
         * @description 로그인 회원을 초대 토큰의 파티 참여자로 생성하거나 기존 참여자를 반환한다. 만료된 초대 토큰 또는 종료된 파티에는 참여자를 생성하지 않는다.
         */
        post: operations["joinPartyInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parties/{partyType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPartyUnknownType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parties/{partyId}/invite-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 파티 초대링크 활성화
         * @description 초대 토큰을 발급하거나 기존 유효 토큰을 재사용한다. 현재 파티 조회/참여 API가 보류되어 토큰 소비 경로는 새 기획 확정 후 다시 연결한다.
         */
        post: operations["activateInviteLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parties/{partyId}/chat-messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 채팅 메시지 전송
         * @description 실시간 파티 채팅에 메시지를 전송합니다.
         *
         *     **전송 가능 조건**
         *     파티가 시작된 상태(`LIVE_OPEN`)에서만 전송할 수 있습니다. 파티 시작 전이나 종료 후에는 전송이 거부됩니다.
         *
         *     **인증**
         *     로그인 사용자는 `Authorization: Bearer {token}` 헤더를, 비로그인 참여자는 `X-Participant-Token: {participantToken}` 헤더를 사용합니다. 둘 중 하나는 반드시 포함해야 합니다.
         *
         *     **전송 후 처리**
         *     메시지가 저장되면 해당 파티의 SSE 구독자 전원에게 `message` 이벤트가 발송됩니다.
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parties/realtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 실시간 파티 생성 */
        post: operations["createRealtimeParty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parties/paper-only": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 롤링페이퍼 파티 생성 */
        post: operations["createPaperOnlyParty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 개발용 JWT 토큰 발급 (존재하지 않으면 유저 자동 생성) */
        post: operations["issueToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/token/by-id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 개발용 JWT 토큰 발급 (userId로) */
        post: operations["issueTokenById"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rolling-paper-wrappers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 롤링페이퍼 래퍼 목록 조회
         * @description 롤링페이퍼 작성 시 선택 가능한 래퍼 목록을 조회한다.
         */
        get: operations["getRollingPaperWrappers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/party-invites/{inviteToken}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 초대장 조회
         * @description 공유 링크 진입 시 초대 토큰으로 파티 요약을 조회한다. 조회 시 participant는 생성하지 않으며, 만료된 초대 토큰도 조회할 수 있다.
         */
        get: operations["getPartyInvite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parties/{partyId}/rolling-papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주최자용 롤링페이퍼 목록 조회
         * @description 인증된 파티 소유자가 롤링페이퍼 목록과 상세 오버레이용 본문을 조회한다.
         */
        get: operations["getOwnerRollingPapers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parties/{partyId}/rolling-papers/{rollingPaperId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주최자용 롤링페이퍼 상세 조회
         * @description 딥링크나 새로고침 복구처럼 목록 page 캐시가 없는 경우 롤링페이퍼 상세 내용을 조회한다.
         */
        get: operations["getOwnerRollingPaperDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/upcoming-parties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 홈 다가오는 파티 목록 조회
         * @description 인증 회원이 참여 중이고 아직 종료되지 않은 파티 목록을 조회한다.
         */
        get: operations["getUpcomingParties"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 캐릭터 목록 조회
         * @description 파티 참여 시 선택 가능한 캐릭터 목록을 조회한다.
         */
        get: operations["getCharacters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 보관함 리스트 조회
         * @description 사용자가 호스트로 만들었거나 참여한 파티 목록을 최신순으로 조회한다. 비로그인은 200 빈 응답을 반환한다.
         */
        get: operations["getArchive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parties/{partyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 파티 삭제 */
        delete: operations["deleteParty"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/parties/{partyId}/realtime-participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 실시간 파티 퇴장
         * @description 실시간 파티 채팅에서 퇴장합니다.
         *
         *     로그인 사용자는 `Authorization: Bearer {token}` 헤더를, 비로그인 참여자는 `X-Participant-Token: {participantToken}` 헤더를 사용합니다.
         *     퇴장하면 현재 SSE 연결이 종료되고, 다른 구독자에게 `user-left` 이벤트가 발송됩니다.
         */
        delete: operations["leaveParty"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 롤링페이퍼 작성 요청 */
        CreateRollingPaperRequest: {
            /**
             * @description 작성자 닉네임
             * @example 축하요정
             */
            writerNickname: string | null;
            /**
             * @description 롤링페이퍼 내용
             * @example 생일 축하해!
             */
            content: string | null;
            /**
             * Format: int64
             * @description 래퍼 ID
             * @example 1
             */
            wrapperId: number | null;
        };
        /** @description 에러 상세 정보 */
        ErrorDetail: {
            /**
             * @description 에러 코드
             * @example PARTY_NOT_FOUND
             */
            code?: string;
            /**
             * @description 에러 메시지
             * @example 파티를 찾을 수 없습니다
             */
            message?: string;
        };
        /** @description 공통 에러 응답 */
        ErrorResponse: {
            /**
             * Format: int32
             * @description HTTP 상태 코드
             * @example 400
             */
            status?: number;
            /** @description 에러 상세 */
            error?: components["schemas"]["ErrorDetail"];
        };
        /** @description 공통 성공 응답 */
        ApiResponseCreateRollingPaperResponse: {
            /**
             * Format: int32
             * @description HTTP 상태 코드
             * @example 200
             */
            status?: number;
            data?: components["schemas"]["CreateRollingPaperResponse"] | null;
        };
        /** @description 롤링페이퍼 작성 응답 */
        CreateRollingPaperResponse: {
            /**
             * Format: int64
             * @description 생성된 롤링페이퍼 ID
             * @example 10
             */
            rollingPaperId?: number;
        };
        EnterRealtimePartyRequest: {
            nickname: string;
            /** Format: int64 */
            characterId?: number;
            participantToken?: string | null;
        };
        /** @description 공통 성공 응답 */
        ApiResponsePartyInviteParticipationResponse: {
            /**
             * Format: int32
             * @description HTTP 상태 코드
             * @example 200
             */
            status?: number;
            data?: components["schemas"]["PartyInviteParticipationResponse"] | null;
        };
        /** @description 초대장 회원 참여 응답 */
        PartyInviteParticipationResponse: {
            /**
             * Format: int64
             * @description 참여자 ID
             * @example 1
             */
            participantId?: number;
        };
        /** @description 초대링크 활성화 응답 */
        ActivateInviteLinkResponse: {
            /**
             * @description 초대 토큰
             * @example example-token-0000
             */
            token?: string;
        };
        /** @description 공통 성공 응답 */
        ApiResponseActivateInviteLinkResponse: {
            /**
             * Format: int32
             * @description HTTP 상태 코드
             * @example 200
             */
            status?: number;
            data?: components["schemas"]["ActivateInviteLinkResponse"] | null;
        };
        SendChatMessageRequest: {
            content: string;
        };
        /** @description 공통 성공 응답 */
        ApiResponseChatMessageResponse: {
            /**
             * Format: int32
             * @description HTTP 상태 코드
             * @example 200
             */
            status?: number;
            data?: components["schemas"]["ChatMessageResponse"] | null;
        };
        ChatMessageResponse: {
            /** Format: int64 */
            messageId?: number;
            content?: string;
            senderNickname?: string;
            /** Format: int64 */
            senderCharacterId?: number | null;
            senderCharacterImageUrl?: string | null;
            /** @enum {string} */
            senderRole?: "CELEBRANT" | "PARTICIPANT";
            /** Format: date-time */
            sentAt?: string;
        };
        /** @description 실시간 파티 생성 요청 */
        CreateRealtimePartyRequest: {
            /**
             * @description 파티 주인공 이름
             * @example 홍길동
             */
            celebrantNickname?: string;
            /**
             * Format: date
             * @description 파티 시작일
             * @example 2024-11-26
             */
            startedDate?: string;
            /**
             * @description 파티 시작 시간 (HH:mm)
             * @example 14:30
             */
            startTime?: string;
            /**
             * Format: int64
             * @description 캐릭터 ID
             * @example 1
             */
            characterId?: number;
        };
        /** @description 공통 성공 응답 */
        ApiResponseCreatePartyResponse: {
            /**
             * Format: int32
             * @description HTTP 상태 코드
             * @example 200
             */
            status?: number;
            data?: components["schemas"]["CreatePartyResponse"] | null;
        };
        CreatePartyResponse: {
            /** Format: int64 */
            partyId?: number;
        };
        /** @description 롤링페이퍼 파티 생성 요청 */
        CreatePaperOnlyPartyRequest: {
            /**
             * @description 파티 주인공 이름
             * @example 홍길동
             */
            celebrantNickname?: string;
            /**
             * Format: date
             * @description 파티 시작일
             * @example 2024-11-26
             */
            startedDate?: string;
        };
        /** @description 공통 성공 응답 */
        ApiResponseDevTokenResponse: {
            /**
             * Format: int32
             * @description HTTP 상태 코드
             * @example 200
             */
            status?: number;
            data?: components["schemas"]["DevTokenResponse"] | null;
        };
        DevTokenResponse: {
            token?: string;
            /** Format: int64 */
            userId?: number;
        };
        /** @description 공통 성공 응답 */
        ApiResponseListRollingPaperWrapperResponse: {
            /**
             * Format: int32
             * @description HTTP 상태 코드
             * @example 200
             */
            status?: number;
            /** @description 응답 데이터 */
            data?: components["schemas"]["RollingPaperWrapperResponse"][] | null;
        };
        /** @description 롤링페이퍼 래퍼 조회 응답 */
        RollingPaperWrapperResponse: {
            /**
             * Format: int64
             * @description 래퍼 ID. 롤링페이퍼 작성 요청의 wrapperId로 전달합니다.
             * @example 1
             */
            wrapperId?: number;
            /**
             * @description 래퍼 이름
             * @example Topping_Candle
             */
            name?: string;
            /**
             * @description 래퍼 이미지 URL
             * @example /images/rolling-paper-wrappers/Topping_Candle.svg
             */
            wrapperImageUrl?: string | null;
        };
        /** @description 공통 성공 응답 */
        ApiResponsePartyInviteLookupResponse: {
            /**
             * Format: int32
             * @description HTTP 상태 코드
             * @example 200
             */
            status?: number;
            data?: components["schemas"]["PartyInviteLookupResponse"] | null;
        };
        /** @description 초대장 조회 응답 */
        PartyInviteLookupResponse: {
            /**
             * Format: int64
             * @description 파티 ID
             * @example 1
             */
            partyId?: number;
            /**
             * @description 파티 주인공 이름
             * @example 홍길동
             */
            celebrantNickname?: string | null;
            /**
             * @description 파티 옵션. REALTIME: 실시간 파티, PAPER_ONLY: 롤링페이퍼 전용 파티
             * @example REALTIME
             * @enum {string}
             */
            partyOption?: "REALTIME" | "PAPER_ONLY";
            /**
             * @description 파티 자체 종료 여부
             * @example false
             */
            partyEnded?: boolean;
            /**
             * @description 현재 조회자의 롤링페이퍼 작성 여부
             * @example false
             */
            rollingPaperWritten?: boolean;
            /**
             * Format: date
             * @description 파티 시작일
             * @example 2026-05-04
             */
            partyStartDate?: string;
            /**
             * Format: date
             * @description 파티 종료일
             * @example 2026-05-11
             */
            partyEndDate?: string;
            realtimeSchedule?: components["schemas"]["RealtimeSchedule"] | null;
            host?: boolean;
        };
        /** @description 실시간 파티 일정 기준 시각 */
        RealtimeSchedule: {
            /**
             * Format: date-time
             * @description 실시간 파티 시작 시각
             * @example 2026-05-04T20:00:00
             */
            liveStartAt?: string;
            /**
             * Format: date-time
             * @description 파티 입장 가능 시작 시각
             * @example 2026-05-04T19:55:00
             */
            enterableFrom?: string;
            /**
             * Format: date-time
             * @description 실시간 파티 종료 시각
             * @example 2026-05-04T20:10:00
             */
            liveEndAt?: string;
            /**
             * Format: int64
             * @description 실시간 파티 진행 시간
             * @example 10
             */
            liveDurationMinutes?: number;
        };
        /** @description 공통 성공 응답 */
        ApiResponseParticipantRollingPaperListResponse: {
            /**
             * Format: int32
             * @description HTTP 상태 코드
             * @example 200
             */
            status?: number;
            data?: components["schemas"]["ParticipantRollingPaperListResponse"] | null;
        };
        /** @description 참가자용 롤링페이퍼 목록 조회 응답 */
        ParticipantRollingPaperListResponse: {
            /**
             * @description 파티 옵션. REALTIME: 실시간 파티, PAPER_ONLY: 롤링페이퍼 전용 파티
             * @example REALTIME
             * @enum {string}
             */
            partyOption?: "REALTIME" | "PAPER_ONLY";
            /**
             * Format: date-time
             * @description 실시간 파티 종료 시각. PAPER_ONLY면 null
             * @example 2026-05-05T22:10:00
             */
            liveEndAt?: string | null;
            /**
             * Format: int32
             * @description 현재 페이지. page가 1보다 작으면 1로 보정합니다.
             * @example 1
             */
            page?: number;
            /**
             * Format: int64
             * @description 전체 롤링페이퍼 수
             * @example 12
             */
            totalCount?: number;
            /**
             * Format: int32
             * @description 전체 페이지 수. 롤링페이퍼가 없으면 0입니다.
             * @example 2
             */
            totalPages?: number;
            /**
             * @description 다음 페이지 존재 여부
             * @example true
             */
            hasNext?: boolean;
            /** @description 롤링페이퍼 목록 */
            items?: components["schemas"]["RollingPaperListItemResponse"][];
        };
        /** @description 롤링페이퍼 목록 item */
        RollingPaperListItemResponse: {
            /**
             * Format: int64
             * @description 롤링페이퍼 ID
             * @example 10
             */
            rollingPaperId?: number;
            /**
             * Format: int64
             * @description 최신순 기준 현재 롤링페이퍼 순번. 1부터 시작합니다.
             * @example 1
             */
            position?: number;
            /**
             * @description 롤링페이퍼 작성자 닉네임
             * @example 축하요정
             */
            writerNickname?: string;
            /**
             * @description 롤링페이퍼 내용. 최대 100자입니다.
             * @example 생일 축하해요!
             */
            content?: string;
            /**
             * @description 롤링페이퍼 래퍼 이미지 URL. 이미지가 없으면 null
             * @example /images/rolling-paper-wrappers/Topping_Candle.svg
             */
            wrapperImageUrl?: string | null;
        };
        /** @description 공통 성공 응답 */
        ApiResponseOwnerRollingPaperListResponse: {
            /**
             * Format: int32
             * @description HTTP 상태 코드
             * @example 200
             */
            status?: number;
            data?: components["schemas"]["OwnerRollingPaperListResponse"] | null;
        };
        /** @description 주최자용 롤링페이퍼 목록 조회 응답 */
        OwnerRollingPaperListResponse: {
            /**
             * @description 파티 주인공 이름
             * @example 홍길동
             */
            celebrantNickname?: string | null;
            /**
             * Format: date-time
             * @description 파티 자체 종료 시각
             * @example 2026-05-12T14:30:00
             */
            partyEndAt?: string;
            /**
             * Format: int32
             * @description 현재 페이지. page가 1보다 작으면 1로 보정합니다.
             * @example 1
             */
            page?: number;
            /**
             * Format: int64
             * @description 전체 롤링페이퍼 수
             * @example 8
             */
            totalCount?: number;
            /**
             * Format: int32
             * @description 전체 페이지 수. 롤링페이퍼가 없으면 0입니다.
             * @example 2
             */
            totalPages?: number;
            /**
             * @description 다음 페이지 존재 여부
             * @example true
             */
            hasNext?: boolean;
            /** @description 롤링페이퍼 목록 */
            items?: components["schemas"]["RollingPaperListItemResponse"][];
        };
        /** @description 공통 성공 응답 */
        ApiResponseOwnerRollingPaperDetailResponse: {
            /**
             * Format: int32
             * @description HTTP 상태 코드
             * @example 200
             */
            status?: number;
            data?: components["schemas"]["OwnerRollingPaperDetailResponse"] | null;
        };
        /** @description 주최자용 롤링페이퍼 상세 조회 응답 */
        OwnerRollingPaperDetailResponse: {
            /**
             * Format: int64
             * @description 롤링페이퍼 ID
             * @example 10
             */
            rollingPaperId?: number;
            /**
             * @description 롤링페이퍼 내용
             * @example 생일 축하해요!
             */
            content?: string;
            /**
             * @description 롤링페이퍼 작성자 닉네임
             * @example 축하요정
             */
            writerNickname?: string;
            /**
             * Format: int64
             * @description 최신순 기준 현재 롤링페이퍼 순번. 1부터 시작합니다.
             * @example 1
             */
            position?: number;
            /**
             * Format: int64
             * @description 파티의 전체 롤링페이퍼 수
             * @example 12
             */
            totalCount?: number;
        };
        /** @description 공통 성공 응답 */
        ApiResponseListUpcomingPartyResponse: {
            /**
             * Format: int32
             * @description HTTP 상태 코드
             * @example 200
             */
            status?: number;
            /** @description 응답 데이터 */
            data?: components["schemas"]["UpcomingPartyResponse"][] | null;
        };
        /** @description 홈 다가오는 파티 응답 */
        UpcomingPartyResponse: {
            /**
             * Format: int64
             * @description 파티 ID
             * @example 1
             */
            partyId?: number;
            /** @description 롤링페이퍼 작성 등에 사용하는 초대 토큰. 유효한 토큰이 없으면 null */
            inviteToken?: string | null;
            /**
             * @description 파티 옵션. REALTIME: 실시간 파티, PAPER_ONLY: 롤링페이퍼 전용 파티
             * @example REALTIME
             * @enum {string}
             */
            partyOption?: "REALTIME" | "PAPER_ONLY";
            /**
             * @description 파티 주인공 이름
             * @example 홍길동
             */
            celebrantNickname?: string | null;
            /**
             * Format: date-time
             * @description 파티 시작 시각
             * @example 2026-05-07T20:00:00
             */
            partyStartedAt?: string;
            /**
             * Format: date-time
             * @description 파티 종료 시각
             * @example 2026-05-14T10:00:00
             */
            partyEndedAt?: string;
            /**
             * @description 현재 회원의 롤링페이퍼 작성 여부
             * @example false
             */
            rollingPaperWritten?: boolean;
            /**
             * Format: date-time
             * @description 주최자 롤링페이퍼 오픈 시각. 주최자가 아니면 null
             */
            hostRollingPaperOpenAt?: string | null;
            realtimeSchedule?: components["schemas"]["UpcomingRealtimeScheduleResponse"] | null;
            host?: boolean;
        };
        /** @description 홈 다가오는 실시간 파티 일정 */
        UpcomingRealtimeScheduleResponse: {
            /**
             * Format: date-time
             * @description 실시간 파티 입장 가능 시작 시각
             * @example 2026-05-07T19:55:00
             */
            enterableFrom?: string;
            /**
             * Format: date-time
             * @description 실시간 파티 시작 시각
             * @example 2026-05-07T20:00:00
             */
            liveStartAt?: string;
            /**
             * Format: date-time
             * @description 실시간 파티 종료 시각
             * @example 2026-05-07T20:10:00
             */
            liveEndAt?: string;
        };
        /** @description 공통 성공 응답 */
        ApiResponseListCharacterResponse: {
            /**
             * Format: int32
             * @description HTTP 상태 코드
             * @example 200
             */
            status?: number;
            /** @description 응답 데이터 */
            data?: components["schemas"]["CharacterResponse"][] | null;
        };
        /** @description 캐릭터 조회 응답 */
        CharacterResponse: {
            /**
             * Format: int64
             * @description 캐릭터 ID. 파티 참여 요청의 characterId로 전달합니다.
             * @example 1
             */
            characterId?: number;
            /**
             * @description 캐릭터 이름
             * @example Default
             */
            name?: string;
            /**
             * @description 캐릭터 이미지 URL
             * @example /images/characters/Type=Default, Shape=Default.png
             */
            characterImageUrl?: string | null;
            /**
             * @description 캐릭터 썸네일 이미지 URL
             * @example /images/character-thumbnails/Type=Default, Shape=Circle.png
             */
            characterThumbnailImageUrl?: string | null;
        };
        /** @description 공통 성공 응답 */
        ApiResponseArchiveListResponse: {
            /**
             * Format: int32
             * @description HTTP 상태 코드
             * @example 200
             */
            status?: number;
            data?: components["schemas"]["ArchiveListResponse"] | null;
        };
        /** @description 보관함 항목 */
        ArchiveListItemResponse: {
            /**
             * @description 항목 ID (participant.id)
             * @example 1024
             */
            id?: string;
            /**
             * @description 항목 타입
             * @example PARTY
             * @enum {string}
             */
            type?: "PARTY" | "PAPER";
            /**
             * @description 파티 이름. 없으면 빈 문자열
             * @example 김루카 생일 파티
             */
            title?: string;
            /**
             * @description 파티 주인공 닉네임. 없으면 null
             * @example 김루카
             */
            celebrantName?: string | null;
            /**
             * Format: date-time
             * @description 파티 종료 시각 (KST 오프셋)
             * @example 2026-05-12T22:10:00+09:00
             */
            date?: string;
        };
        /** @description 보관함 리스트 응답 */
        ArchiveListResponse: {
            /** @description 보관함 항목 */
            items?: components["schemas"]["ArchiveListItemResponse"][];
            /**
             * @description 다음 페이지 cursor. 없으면 null
             * @example 1024
             */
            nextCursor?: string | null;
            /**
             * Format: int64
             * @description 보관함 전체 개수 (헤더 표시용)
             * @example 37
             */
            totalCount?: number;
        };
        /** @description 공통 성공 응답 */
        ApiResponseUserResponse: {
            /**
             * Format: int32
             * @description HTTP 상태 코드
             * @example 200
             */
            status?: number;
            data?: components["schemas"]["UserResponse"] | null;
        };
        UserResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            email?: string;
            /** @enum {string} */
            provider?: "KAKAO" | "GOOGLE" | "APPLE" | "NAVER";
            birthDay?: string;
        };
        /** @description 공통 성공 응답 */
        ApiResponseUnit: {
            /**
             * Format: int32
             * @description HTTP 상태 코드
             * @example 200
             */
            status?: number;
            /** @description 응답 데이터 */
            data?: null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getParticipantRollingPapers: {
        parameters: {
            query?: {
                /**
                 * @description 페이지 번호. 1보다 작으면 1로 보정합니다.
                 * @example 1
                 */
                page?: number;
            };
            header?: never;
            path: {
                /**
                 * @description 초대 토큰
                 * @example exampletoken0000
                 */
                inviteToken: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 참가자용 롤링페이퍼 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseParticipantRollingPaperListResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 파티 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "error": {
                     *         "code": "INTERNAL_SERVER_ERROR",
                     *         "message": "서버 내부 오류가 발생했습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createRollingPaper: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 초대 토큰
                 * @example exampletoken0000
                 */
                inviteToken: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRollingPaperRequest"];
            };
        };
        responses: {
            /** @description 롤링페이퍼 작성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCreateRollingPaperResponse"];
                };
            };
            /** @description 입력값 검증 실패, 만료된 초대 토큰 또는 종료된 파티 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 파티 또는 래퍼 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 닉네임 중복 또는 이미 작성함 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "error": {
                     *         "code": "INTERNAL_SERVER_ERROR",
                     *         "message": "서버 내부 오류가 발생했습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    enterAndSubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 초대 토큰 */
                inviteToken: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnterRealtimePartyRequest"];
            };
        };
        responses: {
            /** @description SSE 스트림 연결 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description 입장 불가 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 리소스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "error": {
                     *         "code": "INTERNAL_SERVER_ERROR",
                     *         "message": "서버 내부 오류가 발생했습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    joinPartyInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 초대 토큰
                 * @example exampletoken0000
                 */
                inviteToken: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 회원 참여자 생성 또는 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePartyInviteParticipationResponse"];
                };
            };
            /** @description 만료된 초대 토큰 또는 종료된 파티 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 존재하지 않는 초대 토큰 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "error": {
                     *         "code": "PARTY_NOT_FOUND",
                     *         "message": "파티를 찾을 수 없습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "error": {
                     *         "code": "INTERNAL_SERVER_ERROR",
                     *         "message": "서버 내부 오류가 발생했습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createPartyUnknownType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    activateInviteLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 파티 ID
                 * @example 1
                 */
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 초대링크 활성화 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseActivateInviteLinkResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 403,
                     *       "error": {
                     *         "code": "PARTY_FORBIDDEN",
                     *         "message": "파티에 대한 권한이 없습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 존재하지 않는 파티 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "error": {
                     *         "code": "PARTY_NOT_FOUND",
                     *         "message": "파티를 찾을 수 없습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "error": {
                     *         "code": "INTERNAL_SERVER_ERROR",
                     *         "message": "서버 내부 오류가 발생했습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: {
                /** @description 비로그인 참여자 토큰 */
                "X-Participant-Token"?: string;
            };
            path: {
                /** @description 파티 ID */
                partyId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendChatMessageRequest"];
            };
        };
        responses: {
            /** @description 메시지 전송 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseChatMessageResponse"];
                };
            };
            /** @description 전송 불가 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 해당 파티의 참여자가 아님 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 403,
                     *       "error": {
                     *         "code": "PARTY_FORBIDDEN",
                     *         "message": "파티에 접근할 수 없습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 파티 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "error": {
                     *         "code": "PARTY_NOT_FOUND",
                     *         "message": "파티를 찾을 수 없습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "error": {
                     *         "code": "INTERNAL_SERVER_ERROR",
                     *         "message": "서버 내부 오류가 발생했습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createRealtimeParty: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRealtimePartyRequest"];
            };
        };
        responses: {
            /** @description 파티 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCreatePartyResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "error": {
                     *         "code": "INTERNAL_SERVER_ERROR",
                     *         "message": "서버 내부 오류가 발생했습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createPaperOnlyParty: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePaperOnlyPartyRequest"];
            };
        };
        responses: {
            /** @description 파티 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCreatePartyResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "error": {
                     *         "code": "INTERNAL_SERVER_ERROR",
                     *         "message": "서버 내부 오류가 발생했습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    issueToken: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDevTokenResponse"];
                };
            };
        };
    };
    issueTokenById: {
        parameters: {
            query: {
                userId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDevTokenResponse"];
                };
            };
        };
    };
    getRollingPaperWrappers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 래퍼 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListRollingPaperWrapperResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "error": {
                     *         "code": "INTERNAL_SERVER_ERROR",
                     *         "message": "서버 내부 오류가 발생했습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPartyInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 초대 토큰
                 * @example exampletoken0000
                 */
                inviteToken: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 초대장 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePartyInviteLookupResponse"];
                };
            };
            /** @description 존재하지 않는 초대 토큰 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 404,
                     *       "error": {
                     *         "code": "PARTY_NOT_FOUND",
                     *         "message": "파티를 찾을 수 없습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "error": {
                     *         "code": "INTERNAL_SERVER_ERROR",
                     *         "message": "서버 내부 오류가 발생했습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOwnerRollingPapers: {
        parameters: {
            query?: {
                /**
                 * @description 페이지 번호. 1보다 작으면 1로 보정합니다.
                 * @example 1
                 */
                page?: number;
            };
            header?: never;
            path: {
                /**
                 * @description 파티 ID
                 * @example 1
                 */
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 주최자용 롤링페이퍼 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOwnerRollingPaperListResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 파티 권한 없음 또는 아직 열람 불가 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 파티 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "error": {
                     *         "code": "INTERNAL_SERVER_ERROR",
                     *         "message": "서버 내부 오류가 발생했습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOwnerRollingPaperDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 파티 ID
                 * @example 1
                 */
                partyId: number;
                /**
                 * @description 롤링페이퍼 ID
                 * @example 10
                 */
                rollingPaperId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 주최자용 롤링페이퍼 상세 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOwnerRollingPaperDetailResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 파티 권한 없음 또는 아직 열람 불가 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 파티 또는 롤링페이퍼 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "error": {
                     *         "code": "INTERNAL_SERVER_ERROR",
                     *         "message": "서버 내부 오류가 발생했습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getUpcomingParties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 다가오는 파티 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListUpcomingPartyResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "error": {
                     *         "code": "INTERNAL_SERVER_ERROR",
                     *         "message": "서버 내부 오류가 발생했습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCharacters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 캐릭터 목록 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListCharacterResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "error": {
                     *         "code": "INTERNAL_SERVER_ERROR",
                     *         "message": "서버 내부 오류가 발생했습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getArchive: {
        parameters: {
            query?: {
                /** @description 마지막으로 받은 항목의 id. 첫 페이지면 생략 */
                cursor?: number;
                /** @description 페이지 크기. 1~50, 기본 20 */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 보관함 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseArchiveListResponse"];
                };
            };
            /** @description 입력값 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 400,
                     *       "error": {
                     *         "code": "VALIDATION_ERROR",
                     *         "message": "nickname: 닉네임은 필수입니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "error": {
                     *         "code": "INTERNAL_SERVER_ERROR",
                     *         "message": "서버 내부 오류가 발생했습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    deleteParty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 파티 ID
                 * @example 1
                 */
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 파티 삭제 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUnit"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "error": {
                     *         "code": "INTERNAL_SERVER_ERROR",
                     *         "message": "서버 내부 오류가 발생했습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    leaveParty: {
        parameters: {
            query?: never;
            header?: {
                /** @description 비로그인 참여자 토큰 */
                "X-Participant-Token"?: string;
            };
            path: {
                /** @description 파티 ID */
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 퇴장 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": 500,
                     *       "error": {
                     *         "code": "INTERNAL_SERVER_ERROR",
                     *         "message": "서버 내부 오류가 발생했습니다"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
